

-- HSQL
INSERT INTO USER2 (ID_USER, EMAIL_USER, FIRSTNAME_USER, LASTNAME_USER, PASSWORD_USER) VALUES (11, 'admin@admin.com','admin','admin','admin');
INSERT INTO USER2 (ID_USER, EMAIL_USER, FIRSTNAME_USER, LASTNAME_USER, PASSWORD_USER) VALUES (12, 'john@gmail.com','john','doe','johndoe');
INSERT INTO USER2 (ID_USER, EMAIL_USER, FIRSTNAME_USER, LASTNAME_USER, PASSWORD_USER) VALUES (13, 'sham@yahoo.com','sham','tis','shamtis');







-- MySQL

-- INSERT INTO USER(EMAIL_USER, FIRSTNAME_USER, LASTNAME_USER, PASSWORD_USER) VALUES ('admin@admin.com','admin','admin','admin');
-- INSERT INTO USER(EMAIL_USER, FIRSTNAME_USER, LASTNAME_USER, PASSWORD_USER) VALUES ('john@gmail.com','john','doe','johndoe');
-- INSERT INTO USER(EMAIL_USER, FIRSTNAME_USER, LASTNAME_USER, PASSWORD_USER) VALUES ('sham@yahoo.com','sham','tis','shamtis');

--SELECT * FROM USER

