
-- HSQL

-- DROP TABLE IF EXISTS USER;

-- create table USER (
--    ID_USER INTEGER GENERATED BY DEFAULT AS IDENTITY,
--    EMAIL_USER varchar(100),
--    FIRSTNAME_USER varchar(100) NOT NULL,
--    LASTNAME_USER varchar(100),
--    PASSWORD_USER varchar(100),
   --DATE_CREATION_USER TIMESTAMP DEFAULT NOW(),
   --DATE_MODIFICATION_USER TIMESTAMP DEFAULT NOW(),
--    PRIMARY KEY (ID_USER)
-- );





-- MySQL

-- create table USER (
-- 	ID_USER integer not null auto_increment, 
-- 	EMAIL_USER varchar(255), 
-- 	FIRSTNAME_USER varchar(255), 
-- 	LASTNAME_USER varchar(255), 
-- 	PASSWORD_USER varchar(255), 
-- 	PRIMARY KEY (ID_USER)
-- ) ENGINE=InnoDB;

